* INTRODUCCIÓN
Arquitectura, proveniente de Árquimedes (referente a correcto) y Tectos
(construcción) hace referencia al correcto diseño de algo. Por otra parte, un
sistema es un conjunto de componentes y conectores organizados con un fin en
común.
** Dinámica del curso
- Clase: Lunes, miercoles y viernes
- Ayudantías: Martes y jueves
- Laboratorio: Jueves, 10-12 hrs
  - Taller de Sistemas Operativos
** Evaluación
*** Examenes parciales
- Primer parcial: jueves 29/02/2024
- Segundo parcial: jueves 11/04/2024
- Tercer parcial: jueves 16/05/2024
*** Calificación final
1. Aprobar el laboratorio (Calificación >= 6)
2. Promedio de los 3 examenes parciales
   - Aprobatorio = Calificación final
   - No aprobatorio => Examen final
** Temario
1. Principios cuantitativos del diseño de arquitecturas
2. Representación de datos en una computadora digital
3. Álgebra Booleana
4. Circuitos combinacionales y secuenciales
5. Diseño del conjunto de instrucciones
6. Unidad de control
7. Cauce segmentado de ejecución (/pipeline/)
8. Relación hardware/software
9. La jerarquía de memoria
10. Entrada/Salida y canales
11. Sistemas multiprocesado
** Recursos didácticos
*** En línea
http://www.matematicas.unam.mx/jloa/curso.orgarqcomp.html
*** Bibliografía
- ComputerArchitecture:	A	QuantitativeApproach,	Hennesy,	J. and Patterson,	D.
  Morgan	Kaufmann, 1996.
- Computer System Architecture.	Mano,	M.M.	Prentice-Hall,	1999.
- Diseño	de	Sistemas	Digitales	y	Arquitectura	de	Computadoras.
  Ortega-Arjona, J.	Facultad de Ciencias, UNAM. 2019.
* APUNTES
** 04/02/2024
*** Datos, información y el concepto de programa almacenado

Procesar datos extrae su significado. Una computadora es una máquina de
procesamiento de datos. Los datos fluyen a la máquina como entrada, e
información fluye desde la maquina como salida.

datos (entrada) => proceso (computadora) => información (salida)

¿Qué hace a una computadora diferente a una calculadora, dado que ambas se
utilizan para hacer operaciones?

Por ejemplo, al sumar, la calculadora encuentra el resultado de la suma, pero el
usuario debe proveer el control mediante decidir que boton presionar. A
diferencia, una computadora procesa datos automáticamente. Se le debe proveer de
un conjunto de instrucciones, en forma de un programa que la guíe. El programa
se almacena dentro de la máquina, y por esto, se le conoce con el nombre de
programa almacenado.

Una *computadora* es una máquina que procesa datos bajo el control de un
programa almacenado a fin de obtener información.

*** La computadora y las cosas que se pueden hacer con ella

La computadora no piensa. Debe ser *programada*, es decir, debe ser dirigida
para realizar un conjunto específico de operaciones. Tal programa (o secuencia
de instrucciones) ha sido almacenado previamente en la computadora.

Las computadoras actuales pueden almacenar una gran cantidad de información. Tal
información consiste tanto en programas que pueden ejecutarse, como de datos
sobre los cuales se ejecutan los programas.

El *programa* puede dirigar a la computadora para realizar, paso a paso,
complejas operaciones, usando tan solo operaciones aritméticas básicas (suma,
resta, multiplicación y división) y algunos otros relativamente simples
procedimientos.

*** Ideas básicas sobre computadoras digitales

Las computadoras digitales operan sobre números. A veces, estos números son
*códigos* que representan instrucciones de un programa, o datos tales como el
nombre de una persona.

Por ejemplo, si se introduce el nombre de una persona a la computadora, debe
convertirse primero en un conjunto de códigos númericos apropiados.

Las computadoras son esencialmente un conjunto de interruptores que se
encuentran en uno de 2 estados: encendido (on) o apagado (off). Así, los
sistemas numéricos trabajan con un sistema numérico de 2 dígitos, llamado
sistema binario, el cual usa 0 y 1 para representar dichos estados de apagado y
encendido respectivamente.

*** Componentes del sistema: componentes básicos
**** Unidad central de proceso (CPU)

Los sistemas de cómputo consisten en una unidad central (que a veces es referida
como la computadora propiamente) y varios periféricos. La unidad central, que
contiene la mayoría de los componentes electrónicos, se conecta mediante cables
a los periféricos.

John von Neumann propone dividir el /hardware/ de la computadora en las
siguientes 5 partes principales:

- Unidad central de proceso
- Entrada
- Salida
- Memoria de trabajo
- Memoria permanente

La *unidad central de proceso* (CPU) es el componente más importante de un
sistema de cómputo. Bajo el control de prógramas almacenados, esta unidad
manipula datos y almacena los resultados en memoria.

Normalmente, la CPU es un circuito único o microprocesador, en el que se
conjuntan la unidad lógico aritmética (ALU por sus siglas en ingles) y la unidad
de control (CU); sin embargo, tal terminología no es completamente estandar, ya
que en algunas computadoras ambas unidades aparecen como elementos
independientes de una computadora.

- La unidad lógico aritmética se encarga de realizar todas las operaciones
  lógicas y aritméticas definidas sobre los valores numéricos binarios. Por
  ejemplo, dos números binarios pueden sumarse para producir un tercero.

- La unidad de control dirige la operación de la computadora. Es el elemento que
  se encarga de controlar el flujo de instrucciones que la computadora va
  llevando a cabo. Por ejemplo, puede dar las instrucciones a la ALU para que
  sume 2 números binarios.

**** Memoria y discos

Todos los datos y los programas cuyas instrucciones los modifican se encuentran
almacenados en la memoria de la computadora digital.

La *memoria* de una computadora almacena tanto datos como programas

En realidad, en una computadora digital, existen varios tipos de unidades de
memoria. Por ejemplo, la *unidad principal de memoria (MMU)* es el almacenamiento
principal y de trabajo de una computadora. Normalmente en computadoras modernas
la memoria principal consiste de circuitos semiconductores.

Un tipo particular de memoria semiconductora es la *memoria de sólo lectura
(/Read Only Memory/ o ROM)*. Este tipo de memoria contiene datos permanente
almacenados, como por ejemplo, podría ser una tabla de valores de funciones
trigonométricas. Tales datos generalmente, aunque no siempre, se incorporan a la
memoria duratne su manufactura.

Otro tipo particular de memoria semiconductora, pero con mayor versatilidad en
su uso durante la ejecución de instrucciones, es la *memoria de acceso aleatorio
(/Random Access Memory/ o RAM)*. Esta memoria es capaz de modificar su estado
mientras permanezca encendida, permitiendo tanto lectura como la escritura de
valores númericos binarios al ejecutar instrucciones de un programa.

Además de la memoria principal, una computadora digital cuenta con también con
*unidades de memoria auxiliar*. Éstas son capaces de almacenar gran cantidad de
información en componentes magnéticos, como son discos o cintas; se consideran
de bajo costo en el sentido de que permiten almacenar muchos datos a un costo
razonable; sin embargo, las operaciones para escribir y leer infroamción toman
mucho más tiempo comparado con el de acceso de la memoria principal
semiconductora.

**** Periféricos

Un *dispositivo periférico* se encuentra alrededor de la computadora, a
diferencia del procesador central o la memoria de trabajo, las cuales forman
parte de la propia computadora.

El número y tipo de dispositivos periféricos dependen de la aplicación principal
que tenga el sistema de cómputo; por ejemplo, teclados, monitores, impresoras, etc.
Se clasifican como:

- Dispositivos de entrada
  Proveen facilidades para la entrada de datos (teclado por ejemplo)

- Dispositivos de salida
  Proveen al usuario con datos y/o información procesada (monitor, impresora)

**** Buses

Los /buses/ se encargan de conectar a la unidad central de proceso con todos los
demás componentes de la computadora. La computadora envía y recibe datos a
traves de los /buses/. Normalmente estos se clasifican como:

- /bus/ del sistema
  Que conecta la unidad central de proceso con la memoria de trabajo RAM

- /buses/ de entrada/salida
  Que conectan a la unidad central de procesamiento con otros componentes

El /bus/ del sistema es la conexión más importante dentro de la computadora, en
tanto los /buses/ de entrada/salida se encargan de transportar datos, conectando
los dispositivos de entrada/salida con la unidad central de proceso y la
memoria.

El *ciclo de entrada/proceso/salida* es la secuencia básica mediante la cual una
computadora procesa datos.

|                           | Unidad central de proceso |                          |
|---------------------------+---------------------------+--------------------------|
|                           | $\uparrow \; \downarrow$  |                          |
| Dispositivo de entrada -> | Memoria principal         | -> Dispositivo de salida |
|                           | $\uparrow \; \downarrow$  |                          |
|---------------------------+---------------------------+--------------------------|
|                           | Memoria secundaria        |                          |

Los componentes físicos de una computadora (unidad central de proceso, memoria y
dispositivos de entrada/salida) se conocen con el nombre genérico de *hardware*.
Los programas y datos sólo existen como pulsos electrónicos que se encuentran en
la memoria, y se les conoce con el nombre genérico de *software*. Una serie de
instrucciones que realiza una tarea en particular se le llama *programa*.
