* INTRODUCCIÓN
Arquitectura, proveniente de Árquimedes (referente a correcto) y Tectos
(construcción) hace referencia al correcto diseño de algo. Por otra parte, un
sistema es un conjunto de componentes y conectores organizados con un fin en
común.
** Dinámica del curso
- Clase: Lunes, miercoles y viernes
- Ayudantías: Martes y jueves
- Laboratorio: Jueves, 10-12 hrs
  - Taller de Sistemas Operativos
** Evaluación
*** Examenes parciales
- Primer parcial: jueves 29/02/2024
- Segundo parcial: jueves 11/04/2024
- Tercer parcial: jueves 16/05/2024
*** Calificación final
1. Aprobar el laboratorio (Calificación >= 6)
2. Promedio de los 3 examenes parciales
   - Aprobatorio = Calificación final
   - No aprobatorio => Examen final
** Temario
1. Principios cuantitativos del diseño de arquitecturas
2. Representación de datos en una computadora digital
3. Álgebra Booleana
4. Circuitos combinacionales y secuenciales
5. Diseño del conjunto de instrucciones
6. Unidad de control
7. Cauce segmentado de ejecución (/pipeline/)
8. Relación hardware/software
9. La jerarquía de memoria
10. Entrada/Salida y canales
11. Sistemas multiprocesado
** Recursos didácticos
*** En línea
http://www.matematicas.unam.mx/jloa/curso.orgarqcomp.html
*** Bibliografía
- ComputerArchitecture:	A	QuantitativeApproach,	Hennesy,	J. and Patterson,	D.
  Morgan	Kaufmann, 1996.
- Computer System Architecture.	Mano,	M.M.	Prentice-Hall,	1999.
- Diseño	de	Sistemas	Digitales	y	Arquitectura	de	Computadoras.
  Ortega-Arjona, J.	Facultad de Ciencias, UNAM. 2019.
* APUNTES
** 04/02/2024
*** Datos, información y el concepto de programa almacenado

Procesar datos extrae su significado. Una computadora es una máquina de
procesamiento de datos. Los datos fluyen a la máquina como entrada, e
información fluye desde la maquina como salida.

datos (entrada) => proceso (computadora) => información (salida)

¿Qué hace a una computadora diferente a una calculadora, dado que ambas se
utilizan para hacer operaciones?

Por ejemplo, al sumar, la calculadora encuentra el resultado de la suma, pero el
usuario debe proveer el control mediante decidir que boton presionar. A
diferencia, una computadora procesa datos automáticamente. Se le debe proveer de
un conjunto de instrucciones, en forma de un programa que la guíe. El programa
se almacena dentro de la máquina, y por esto, se le conoce con el nombre de
programa almacenado.

Una *computadora* es una máquina que procesa datos bajo el control de un
programa almacenado a fin de obtener información.

*** La computadora y las cosas que se pueden hacer con ella

La computadora no piensa. Debe ser *programada*, es decir, debe ser dirigida
para realizar un conjunto específico de operaciones. Tal programa (o secuencia
de instrucciones) ha sido almacenado previamente en la computadora.

Las computadoras actuales pueden almacenar una gran cantidad de información. Tal
información consiste tanto en programas que pueden ejecutarse, como de datos
sobre los cuales se ejecutan los programas.

El *programa* puede dirigar a la computadora para realizar, paso a paso,
complejas operaciones, usando tan solo operaciones aritméticas básicas (suma,
resta, multiplicación y división) y algunos otros relativamente simples
procedimientos.

*** Ideas básicas sobre computadoras digitales

Las computadoras digitales operan sobre números. A veces, estos números son
*códigos* que representan instrucciones de un programa, o datos tales como el
nombre de una persona.

Por ejemplo, si se introduce el nombre de una persona a la computadora, debe
convertirse primero en un conjunto de códigos númericos apropiados.

Las computadoras son esencialmente un conjunto de interruptores que se
encuentran en uno de 2 estados: encendido (on) o apagado (off). Así, los
sistemas numéricos trabajan con un sistema numérico de 2 dígitos, llamado
sistema binario, el cual usa 0 y 1 para representar dichos estados de apagado y
encendido respectivamente.

*** Componentes del sistema: componentes básicos
**** Unidad central de proceso (CPU)

Los sistemas de cómputo consisten en una unidad central (que a veces es referida
como la computadora propiamente) y varios periféricos. La unidad central, que
contiene la mayoría de los componentes electrónicos, se conecta mediante cables
a los periféricos.

John von Neumann propone dividir el /hardware/ de la computadora en las
siguientes 5 partes principales:

- Unidad central de proceso
- Entrada
- Salida
- Memoria de trabajo
- Memoria permanente

La *unidad central de proceso* (CPU) es el componente más importante de un
sistema de cómputo. Bajo el control de prógramas almacenados, esta unidad
manipula datos y almacena los resultados en memoria.

Normalmente, la CPU es un circuito único o microprocesador, en el que se
conjuntan la unidad lógico aritmética (ALU por sus siglas en ingles) y la unidad
de control (CU); sin embargo, tal terminología no es completamente estandar, ya
que en algunas computadoras ambas unidades aparecen como elementos
independientes de una computadora.

- La unidad lógico aritmética se encarga de realizar todas las operaciones
  lógicas y aritméticas definidas sobre los valores numéricos binarios. Por
  ejemplo, dos números binarios pueden sumarse para producir un tercero.

- La unidad de control dirige la operación de la computadora. Es el elemento que
  se encarga de controlar el flujo de instrucciones que la computadora va
  llevando a cabo. Por ejemplo, puede dar las instrucciones a la ALU para que
  sume 2 números binarios.

**** Memoria y discos

Todos los datos y los programas cuyas instrucciones los modifican se encuentran
almacenados en la memoria de la computadora digital.

La *memoria* de una computadora almacena tanto datos como programas

En realidad, en una computadora digital, existen varios tipos de unidades de
memoria. Por ejemplo, la *unidad principal de memoria (MMU)* es el almacenamiento
principal y de trabajo de una computadora. Normalmente en computadoras modernas
la memoria principal consiste de circuitos semiconductores.

Un tipo particular de memoria semiconductora es la *memoria de sólo lectura
(/Read Only Memory/ o ROM)*. Este tipo de memoria contiene datos permanente
almacenados, como por ejemplo, podría ser una tabla de valores de funciones
trigonométricas. Tales datos generalmente, aunque no siempre, se incorporan a la
memoria duratne su manufactura.

Otro tipo particular de memoria semiconductora, pero con mayor versatilidad en
su uso durante la ejecución de instrucciones, es la *memoria de acceso aleatorio
(/Random Access Memory/ o RAM)*. Esta memoria es capaz de modificar su estado
mientras permanezca encendida, permitiendo tanto lectura como la escritura de
valores númericos binarios al ejecutar instrucciones de un programa.

Además de la memoria principal, una computadora digital cuenta con también con
*unidades de memoria auxiliar*. Éstas son capaces de almacenar gran cantidad de
información en componentes magnéticos, como son discos o cintas; se consideran
de bajo costo en el sentido de que permiten almacenar muchos datos a un costo
razonable; sin embargo, las operaciones para escribir y leer infroamción toman
mucho más tiempo comparado con el de acceso de la memoria principal
semiconductora.

**** Periféricos

Un *dispositivo periférico* se encuentra alrededor de la computadora, a
diferencia del procesador central o la memoria de trabajo, las cuales forman
parte de la propia computadora.

El número y tipo de dispositivos periféricos dependen de la aplicación principal
que tenga el sistema de cómputo; por ejemplo, teclados, monitores, impresoras, etc.
Se clasifican como:

- Dispositivos de entrada
  Proveen facilidades para la entrada de datos (teclado por ejemplo)

- Dispositivos de salida
  Proveen al usuario con datos y/o información procesada (monitor, impresora)

**** Buses

Los /buses/ se encargan de conectar a la unidad central de proceso con todos los
demás componentes de la computadora. La computadora envía y recibe datos a
traves de los /buses/. Normalmente estos se clasifican como:

- /bus/ del sistema
  Que conecta la unidad central de proceso con la memoria de trabajo RAM

- /buses/ de entrada/salida
  Que conectan a la unidad central de procesamiento con otros componentes

El /bus/ del sistema es la conexión más importante dentro de la computadora, en
tanto los /buses/ de entrada/salida se encargan de transportar datos, conectando
los dispositivos de entrada/salida con la unidad central de proceso y la
memoria.

El *ciclo de entrada/proceso/salida* es la secuencia básica mediante la cual una
computadora procesa datos.

|                           | Unidad central de proceso |                          |
|---------------------------+---------------------------+--------------------------|
|                           | $\uparrow \; \downarrow$  |                          |
| Dispositivo de entrada -> | Memoria principal         | -> Dispositivo de salida |
|                           | $\uparrow \; \downarrow$  |                          |
|---------------------------+---------------------------+--------------------------|
|                           | Memoria secundaria        |                          |

**** Hardware y Software

Los componentes físicos de una computadora (unidad central de proceso, memoria y
dispositivos de entrada/salida) se conocen con el nombre genérico de *hardware*.
Los programas y datos sólo existen como pulsos electrónicos que se encuentran en
la memoria, y se les conoce con el nombre genérico de *software*. Una serie de
instrucciones que realiza una tarea en particular se le llama *programa*.

Las dos categorías más importantes en que se clasifica el /software/ son:
***** Software
****** Software del sistema

El *software del sistema* se refiere a los programas que se utilizan para
controlar la computadora y desarrollar y ejecutar /software de aplicación/ (o
simplemente aplicaciones).

****** Software de aplicación

El *software de aplicación* es cualquier entrada de datos, actualización,
solicitud, reporte u otro programa que procesa datos para el usuario. El
/software de aplicación/ incluye los paquetes genéricos de /software/ (hojas de
calculo, procesadores de palabras, programas de bases de datos, etc) así como
programas de paquetería o hechos a la medida como nóminas, pagos, inventarios, y
otros.
***** Hardware

El /hardware/ se encarga del almacenamiento  y la transmisión. Mientras más
memoria y almacenamiento en disco tenga una computadora, más trabajo puede
realizar. Mientras más rápida sea la memoria y los discos para transmitir datos
e instrucciones al CPU, más rápido se realiza el trabajo.

*** Estudiando la arquitectura de sistemas de cómputo

La siguiente tabla muestra como se construyen diferentes niveles de estudio y
abstracción sobre descripciones más simples. Aquí, de abajo hacia arriba, se
comienza describiendo a los elementos lógicos que forman los bloques básicos de
construcción del /hardware/ de un sistema de cómputo, y que se combinan para
obtener una máquina simple de cómputo. Después de esto, se provee alguna
información introductoria de los sistemas operativos. Los dos últimos niveles
más altos en el estudio de sistemas de cómputo, lenguajes de programación de
alto nivel y aplicaciones, no forman parte del objeto de estudio de este curso.

| aplicaciones      |
|-------------------|
| lenguajes de      |
| programación de   |
| alto nivel        |
|-------------------|
| sistema operativo |
|-------------------|
| máquina           |
|-------------------|
| elementos lógicos |

** 06/02/2024
*** Sistema numérico binario

El sistema utilizado en las computadoras para representar y procesar datos e
información es el *sistema numérico binario*, o base 2. Cualquier número puede
representarse usando dos simbolos: /0/ y /1/, mediante utilizar la misma
notación posicional como en el sistema decimal. Un dígito binario se conoce como
*bit* (*b* inary dig *it*)

*¿Cuantos bits se necesitan?* La regla general es con /n/ bits se pueden
 representar los números del 0 al (2^n-1). En un sistema de cómputo, un grupo de
 8 bits se conoce como /byte/ y puede representar números del 0 al 255.

*** Sistemas octal y hexadecimal

Los sistemas numéricos octal (base 8) y hexadecimal (base 16) prooven de una
representación más corta y clara para números con múltiples bits en un sistema
digital, dado que sus bases son potencias de 2.

El sistema octal utiliza los dígitos del 0 al 7 del sistema decimal, dado que
solo requiere 8 dígitos para representar números.

El sistema hexadecimal utiliza los dígitos del 0 al 9 y las letras A, B, C, D, E
y F, dado que requiere de 16 símbolos para representar cualquier número.

La utilidad de los sistemas octal y decimal radica en que representan una forma
más compacta de los números binarios y es relativamente fácil convertirlos a
binario.

Para convertir un número binario a octal, se procede en los siguientes pasos:

1. Comenzando por el extremo derecho de la cadena de bits binarios, y hacia la
   izquierda.

2. Se añaden ceros a la izquierda hasta hacer el número total de bits un
   múltiplo de 3.

3. Se separan en grupos de 3.

4. Se remplaza cada grupo de bits con el correspondiente dígito octal.

El procedimiento para convertir de binario a hexadecimal es similar, excepto que
se forman y remplazan grupos de 4 bits.

*** Parte fraccional

El punto que separa la parte entera de la parte fraccionaria se llama punto
decimal para la base 10. En el caso general, se llama punto a la base, en
particular, en base 2 se llama punto binario, en base 8 se llama punto octal y
en base 16, punto hexadecimal.

Las fracciones binarias se presentan en un número binario, como por ejemplo
0.101_2 tiene:

                         1 mitad + 0 cuartos + 1 octavo

Y por lo tanto, se tiene que:

$0.101_2 = 1 \times 2^{-1} + 0 \times 2^{-2} + 1 \times 2^{-3} = 0.5 + 0 + 0.125 = 0.625_{10}$

*** Cambiando de una base a otra
**** Decimal a binario

Para esto se hace necesario obtener cuántos dígitos binarios se encuentran en la
primera posición del número entero, es decir, el dígito que se multiplica por
2⁰. Para hacer esto, se divide el número entre 2, por ejemplo para 53_10:

53/2 = 26 + 1/2

El residuo de la división (en este caso 1) representa el dígito binario del
número multiplicado por 2⁰. Este proceso se repite obteniendo 2¹, 2², etc.

A continuación, se examina cómo una fracción expresada en base 10, puede
convertirse en binario. En este caso, el proceso involucra la multiplicación con
la base en lugar de la división entre la base, como en el caso de los números
enteros. Por ejemplo, considerese el equivalente binario de 0.125_10:

                                0.125 * 2 = 0.25

La parte entera del resultado es 0, por lo que el digito binario que multiplica
a 2^-1 es 0. Repitiendo este proceso obtenemos el número binario 0.001_2.

La conversión de algunas fracciones decimales a su equivalente binario puede
resultar en algunas inexactitutdes, ya que ni las personas ni las computadoras
pueden trabajar con un número infinito de términos. Tal inexactitud se conoce
como *error de redondeo* (/round-off error/). El uso de suficientes términos
puede hacer que la inexactitud sea despreciable.

Tambien es importante recalcar que cuando se convierte un número que consta
tanto de parte entera como fraccional, la conversión se hace por separado.

**** Decimal a octal/hexadecimal

Si se desea convertir un número decimal a su equivalente octal o hexadecimal, se
utiliza el mismo procedimiento, excepto que en el caso octal se
divide/multiplica por 8 y en el hexadecimal, se utiliza el 16.

*** Aritmética binaria elemental
